name: fitness_plus
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  charts_painter: ^3.0.0
  fl_chart: ^0.55.2
  line_icons: ^2.0.1
  flutter_svg: ^1.1.6
  sqflite: ^2.2.0+3
  path_provider: ^2.0.11
  grouped_list: ^5.1.2
  flutter_icons_null_safety: ^1.1.0
  responsive_framework: ^0.2.0
  google_maps_flutter: ^2.2.1
  http: ^0.13.5
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  google_maps_flutter_web: ^0.4.0+3
  google_maps_flutter_android: ^2.3.3
  google_maps_flutter_ios: ^2.1.12
  date_format: ^2.0.7
  url_launcher: ^6.1.6
  flutter_vector_icons: ^2.0.0
  ionicons: ^0.2.1
  iconly: ^1.0.1
  font_awesome_flutter: ^10.2.1
  flutter_local_notifications: ^12.0.3
  googleapis: ^9.2.0
  map_launcher: ^2.4.0
  rflutter_alert: ^2.0.4
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.10.0
  permission_handler: ^10.2.0
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
